require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*

Metrics/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - proforma.gemspec

RSpec/NestedGroups:
  Max: 5
