require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/**/*
    - Guardfile

Layout/LineLength:
  Max: 140

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/EmptyBlock:
  Exclude:
    - spec/**/*
    - lib/proforma/services/exporter.rb

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - proforma.gemspec

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/custom_matchers/*
