require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - proforma.gemspec

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
