require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - vendor/**/*
    - Guardfile

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - proforma.gemspec

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/custom_matchers/*
