os: linux
dist: xenial

language: ruby

rvm:
  - 2.7.2

cache:
  bundler: true

addons:
  code_climate:
    repo_token: 48cde6480e68e3533a4919a6f80421c1bc4e1964250a33ea5bb3427acfc1da27

before_install:
  - gem install bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec spec/
  - bundle exec rubocop

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
